name: 'Commit To Repo'
description: 'Commits local files specified to a repository.'
inputs:
  branch:
    description: 'An optional repository branch to checkout and commit to. Will use whatever the default branch of the destination repo is, if not specified.'
    required: false
    default: ''
  files:
    description: 'A list of local files to commit.'
    required: true
  github-pat:
    description: 'A custom token to use.'
    required: false
    default: ''
  github-app-id:
    description: 'The app ID of a Github App. Do not provide if github-pat-token is provided.'
    required: false
    default: ''
  github-app-private-key:
    description: 'The private key for a Github App. Do not provide if github-pat-token is provided.'
    required: false
  github-owner:
    description: 'The Github owner of the repository.'
    required: true
  github-repository:
    description: 'The Github repository to commit to.'
    required: true
  path:
    description: 'An optional path in the destination repository to place the files.'
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Output PAT To Environment
      if: ${{ inputs.github-pat != '' }}
      shell: bash
      run: |
        echo "Attempting to use PAT credential...";
        echo "GITHUB_TOKEN=${{ inputs.github-pat }}" >> ${GITHUB_ENV}

    - name: Get Token From App
      if: ${{ inputs.github-app-id != '' && inputs.github-app-private-key != '' }}
      id: app-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.github-app-id }}
        private-key: ${{ inputs.github-app-private-key }}
        owner: ${{ inputs.github-owner }}
        repositories: ${{ inputs.github-repository }}

    - name: Output App Token To Environment
      if: ${{ inputs.github-app-id != '' && inputs.github-app-private-key != '' }}
      shell: bash
      run: |
        echo "Attempting to use Github App credentials..."
        echo "GITHUB_TOKEN=${{ steps.app-token.outputs.token }}" >> ${GITHUB_ENV}

    - name: Validate Destination Directory Doesn't Exist
      shell: bash
      run: |
        # make sure the destination directory doesn't exist
        rm -rf ${{ inputs.github-repository }}

    - name: Clone Destination Repo
      shell: bash
      run: |
        # only provide branch if specified
        BRANCH=""
        if [[ ! -z "${{ inputs.branch }}" ]]; then
          BRANCH="-b ${{ inputs.branch }}";
        fi

        # clone the repo
        git clone ${BRANCH} https://x-access-token:${GITHUB_TOKEN}@github.com/${{ inputs.github-owner }}/${{ inputs.github-repository }}.git

    - name: Configure Git
      shell: bash
      working-directory: ${{ inputs.github-repository }}
      run: |
        git config user.email "commit-to-repo@tensure.io"
        git config user.name "CommitBot"

    - name: Validate Destination Path Exists
      shell: bash
      working-directory: ${{ inputs.github-repository }}
      run: |
        # make sure destination path exists
        mkdir -p "${{ inputs.path }}"

    - name: Add Files Specified
      shell: bash
      working-directory: ${{ inputs.github-repository }}
      run: |
        # loop over files
        while IFS= read -r FILE; do
          cp ../${FILE} ${{ inputs.path }}/${FILE}
          git add ${{ inputs.path }}/${FILE}
        done <<< '${{ inputs.files }}'

    - name: Commit Changes
      shell: bash
      working-directory: ${{ inputs.github-repository }}
      run: |
        git commit -m "Patched in ${{ github.repository }}@${GITHUB_SHA}" && git push origin